daraz_categories = {
    "electronic devices":
        {"Smartphones": "https://www.daraz.com.bd/smartphones/",
        "Feature Phone": "https://www.daraz.com.bd/featurephones",
        "Tablets": "https://www.daraz.com.bd/tablets/",
        "Laptops": "https://www.daraz.com.bd/laptops",
        "Desktops": "https://www.daraz.com.bd/desktop-computer",
        "Gaming Consoles": "https://www.daraz.com.bd/gaming-consoles",
        "Cameras": "https://www.daraz.com.bd/camera",
        "Security Cameras": "https://www.daraz.com.bd/security-cameras"
        },
    "electronic accessories":
        {"Mobile Accessories": "https://www.daraz.com.bd/mobiles-tablets-accessories",
        "Audio": "https://www.daraz.com.bd/audio",
        "Wearable": "https://www.daraz.com.bd/wearable-technology",
        "Console Accessories": "https://www.daraz.com.bd/gaming-consoles",
        "Camera Accessories": "https://www.daraz.com.bd/camera-accessories",
        "Computer Accessories": "https://www.daraz.com.bd/computing-peripherals-accessories",
        "Storage": "https://www.daraz.com.bd/computing-storage",
        "Printer": "https://www.daraz.com.bd/printers-scanners",
        "Computer Components": "https://www.daraz.com.bd/components-spare-parts",
        "Network Components": "https://www.daraz.com.bd/networking",
        "Software": "https://www.daraz.com.bd/software"
        },
    "tv & home appliances":
        {"Television": "https://www.daraz.com.bd/televisions",
        "Home Audio": "https://www.daraz.com.bd/audio",
        "TV Accessories & Video Device": "https://www.daraz.com.bd/tv-accessories",
        "Large Appliances": "https://www.daraz.com.bd/cooking-appliances",
        "Small Kitchen Appliances": "https://www.daraz.com.bd/small-kitchen-appliances",
        "Cooking & Heating": "https://www.daraz.com.bd/cooling-heating",
        "Fan": "https://www.daraz.com.bd/all-fans",
        "Vacuums & Floor Care": "https://www.daraz.com.bd/floorcare-appliances",
        "Irons & Germent Steamers": "https://www.daraz.com.bd/garment-care",
        "Water Purifiers & Filters": "https://www.daraz.com.bd/water-dispensers-purifiers"
        },
    "health & beauty":
        {"Bath & Body": "https://www.daraz.com.bd/bath-body",
        "Beauty Tools": "https://www.daraz.com.bd/health-beauty-tools",
        "Fragrances": "https://www.daraz.com.bd/fragrances",
        "Hair Care": "https://www.daraz.com.bd/hair-care-beauty",
        "Makeup": "https://www.daraz.com.bd/womens-make-up",
        "Men's Care": "https://www.daraz.com.bd/mens-grooming",
        "Personal Care": "https://www.daraz.com.bd/personal-care",
        "Skin Care": "https://www.daraz.com.bd/skincare-beauty",
        "Food Supplements": "https://www.daraz.com.bd/health-supplements/",
        "Medical Supplies": "https://www.daraz.com.bd/health-care",
        "Sexual Wellness": "https://www.daraz.com.bd/sexual-wellness"
        },
    "babies & toys":
        {"Mother & Baby": "https://www.daraz.com.bd/mother-baby",
        "Feeding": "https://www.daraz.com.bd/feeding",
        "Diapering & Potty": "https://www.daraz.com.bd/baby-toddler-diapers-potties",
        "Baby Gear": "https://www.daraz.com.bd/baby-gear",
        "Baby Personal Care": "https://www.daraz.com.bd/baby-personal-care",
        "Clothing & Accessories": "https://www.daraz.com.bd/baby-clothings-accessories",
        "Nursery": "https://www.daraz.com.bd/baby-toddler-nursery",
        "Toys & games": "https://www.daraz.com.bd/toys-games",
        "Baby & Todler Toys": "https://www.daraz.com.bd/baby-toddler-toys-games/",
        "Remote Control & Vehicles": "https://www.daraz.com.bd/remote-control-toys-and-play-vehicles",
        "Sports & Outdoor Play": "https://www.daraz.com.bd/sports-and-outdoor-play",
        "Traditional Games": "https://www.daraz.com.bd/traditional-games",
        },
    "groceries & pets":
        {"Beverages": "https://www.daraz.com.bd/beverages",
        "Breakfast, Choco & Snacks": "https://www.daraz.com.bd/breakfast",
        "Food Staples": "https://www.daraz.com.bd/baking-and-cooking",
        "Cooking Ingredients": "https://www.daraz.com.bd/groceries-baking-cooking-cooking-ingredients",
        "Laudry & Household": "https://www.daraz.com.bd/laundry-and-home-care",
        "Cat": "https://www.daraz.com.bd/cats-supplies",
        "Dog": "https://www.daraz.com.bd/dogs-supplies",
        "Fish": "https://www.daraz.com.bd/fish",
        "Bird": "https://www.daraz.com.bd/bird",
        "Small Pet": "https://www.daraz.com.bd/small-pet",
        "Lifestyle Accessories": "https://www.daraz.com.bd/gr-cigars-&-cigarettes"
        },
    "home & lifestyle":
        {"Bath": "https://www.daraz.com.bd/bath",
        "Bedding": "https://www.daraz.com.bd/bedding",
        "Decor": "https://www.daraz.com.bd/home-decoration",
        "Furniture": "https://www.daraz.com.bd/furniture",
        "Kitchen & Dining": "https://www.daraz.com.bd/kitchen-dining",
        "Lighting": "https://www.daraz.com.bd/lighting",
        "Laundry & Cleaning": "https://www.daraz.com.bd/laundry-cleaning",
        "Tools, DIY & Outdoor": "https://www.daraz.com.bd/home-improvement",
        "Stationary & Craft": "https://www.daraz.com.bd/stationery-craft/",
        "Media, Music & Books": "https://www.daraz.com.bd/books-games-music"
        },
    "women's fashion":
        {"Sweaters & Cardigans": "https://www.daraz.com.bd/womens-sweaters/",
        "Jackets & Coats": "https://www.daraz.com.bd/women-jackets-coats/",
        "Sarees": "https://www.daraz.com.bd/womens-sarees/",
        "Shalwar Kameez": "https://www.daraz.com.bd/womens-shalwar-kameez/",
        "Unstitch Fabric": "https://www.daraz.com.bd/womens-lawn/",
        "Kurtis": "https://www.daraz.com.bd/womens-kurtis/",
        "Clothing": "https://www.daraz.com.bd/womens-clothing/",
        "Women's Bags": "https://www.daraz.com.bd/womens-bags/",
        "Shoes": "https://www.daraz.com.bd/womens-shoes/",
        "Accessories": "https://www.daraz.com.bd/womens-accessories/",
        "Lingerie, Sleep & Lounge": "https://www.daraz.com.bd/womens-lingerie-sleepwear/",
        "Travel & Luggage": "https://www.daraz.com.bd/travels/"
        },
    "men's fashion":
        {"Jackets & Coats": "https://www.daraz.com.bd/men-jackets-coats/",
        "Hoodies & Sweatshirts": "https://www.daraz.com.bd/mens-hoodies/",
        "Sweaters": "https://www.daraz.com.bd/men-sweaters-cardigans/",
        "T-Shirts": "https://www.daraz.com.bd/mens-t-shirts/",
        "Shirts": "https://www.daraz.com.bd/mens-shirts/",
        "Polo Shirts": "https://www.daraz.com.bd/mens-polo-shirts/",
        "Jeans": "https://www.daraz.com.bd/mens-jeans/",
        "Pant": "https://www.daraz.com.bd/mens-pants-trousers/",
        "Men's Bags": "https://www.daraz.com.bd/mens-bags/",
        "Shoes": "https://www.daraz.com.bd/mens-shoes/",
        "Accessories": "https://www.daraz.com.bd/men-accessories/",
        "Clothing": "https://www.daraz.com.bd/mens-clothing/"
        },
    "watches & accessories":
        {"Men's watch": "https://www.daraz.com.bd/mens-watches/",
        "Women's watch": "https://www.daraz.com.bd/womens-watches/",
        "Women's Jewelleries": "https://www.daraz.com.bd/shop-womens-jewellery/",
        "Men's Jewelleries": "https://www.daraz.com.bd/mens-fashion-jewellery",
        "Fashion Mask": "https://www.daraz.com.bd/fashion-masks/",
        "Men's Belt": "https://www.daraz.com.bd/mens-belts/",
        "Men's Wallet": "https://www.daraz.com.bd/mens-sports-wallets/",
        "Sunglasses": "https://www.daraz.com.bd/mens-sunglasses/",
        "Eyeglasses": "https://www.daraz.com.bd/eyeglasses/",
        "Kid's Watch": "https://www.daraz.com.bd/kids-watches-wsj/"
        },
    "sports & outdoors":
        {"Treadmills": "https://www.daraz.com.bd/treadmills/",
        "Fitness Accessories": "https://www.daraz.com.bd/weights-accessories/",
        "Dumbbells": "https://www.daraz.com.bd/dumbells/",
        "Cycling": "https://www.daraz.com.bd/cycling/",
        "Boxing, Martial Arts & MMA": "https://www.daraz.com.bd/boxing-martial-arts-mma/",
        "Shoes & Clothing": "https://www.daraz.com.bd/mens-sports/",
        "Outdoor Recreation": "https://www.daraz.com.bd/outdoor-activities/",
        "Exercise & Fitness": "https://www.daraz.com.bd/exercise-fitness/",
        "Racket Sports": "https://www.daraz.com.bd/racket-sports/",
        "Team Sports": "https://www.daraz.com.bd/team-sports/",
        "Camping & Hiking": "https://www.daraz.com.bd/camping-hiking/",
        "Fanshop": "https://www.daraz.com.bd/fan-shop-collectibles/"
        },
    "automotive & motorbike":
        {"Automobile": "https://www.daraz.com.bd/automotive/",
        "Auto Oils & Fluids": "https://www.daraz.com.bd/oils-fluids/",
        "Interior Accessories": "https://www.daraz.com.bd/interior-accessories/",
        "Exterior Accessories": "https://www.daraz.com.bd/exterior-accessories/",
        "Exterior Vehicle Care": "https://www.daraz.com.bd/automotive-exterior-vehicle-care/?spm=a2a0e.searchlist.breadcrumb.4.5e3f7bcajkpofL",
        "Interior Vehicle Care": "https://www.daraz.com.bd/interior-care/?spm=a2a0e.pdp.breadcrumb.3.7571265e1sc5X8",
        "Car Electronic Accessories": "https://www.daraz.com.bd/car-electronics-accessories/?spm=a2a0e.searchlist.breadcrumb.4.759170731SA4sH",
        "Car Audio": "https://www.daraz.com.bd/car-audio/",
        "Motorcycle": "https://www.daraz.com.bd/automotive-motorcycles/",
        "Moto Parts & Accessories": "https://www.daraz.com.bd/motorcycle-parts-spares/",
        "Motorcycle Riding Gear": "https://www.daraz.com.bd/motorcycle-riding-gear/"
        }
}
